dist: trusty
sudo: false

language: scala
scala:
  - 2.12.6
  - 2.11.12

jdk:
  - oraclejdk8

services:
  - docker

script:
   - sbt ++$TRAVIS_SCALA_VERSION fullCiBuild

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

before_install:
  - docker run -d --name socket-relay -v /var/run/docker.sock:/var/run/docker.sock -p 127.0.0.1:1717:1717 bobrik/socat TCP-LISTEN:1717,fork UNIX-CONNECT:/var/run/docker.sock

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

after_success:
  - docker kill socket-relay
  - docker rm socket-relay