dist: trusty
sudo: false

language: scala
scala:
  - 2.12.12
  - 2.13.3

jdk:
  - openjdk8
  - openjdk11

services:
  - docker

cache:
  directories:
  - "$HOME/.coursier/cache"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
  - find $HOME/.ivy2/cache -name "*.lock" | xargs rm -rf
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete

script:
   - sbt ++$TRAVIS_SCALA_VERSION fullCiBuild