addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("com.github.sbt"   % "sbt-release"          % "1.1.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"         % "3.9.10")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"              % "2.1.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.4")
